### ISSUE TITLE
recursion_limit gpt-3.5

### ISSUE THREAD

**Issue by MyraBaba** [brainqub3/meta_expert#1]
Hi,

Question is : Tell me today weather in Paris..

after a while:

langgraph.errors.GraphRecursionError: Recursion limit of 40 reachedwithout hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.

**Comment by BruceSuperProgramer** [comment]
Yep, I had same problem.

**Comment by john-adeojo** [comment]
Assuming you're using the jar3d, navigate to the bottom of the jar3d.py script. You can change the recursion limit there.

![Screenshot_20240729-151644_GitHub.jpg](https://github.com/user-attachments/assets/dcdf4496-6b07-4a65-af37-cf2d40636297)

**Comment by john-adeojo** [comment]
The most recent commit uses Docker to get up and running with Jar3d. The approach should cause less errors, please give it a try and let me know how it goes.
