### ISSUE TITLE
Switch from Markdown to XML

### ISSUE THREAD

**Issue by manjaroblack** [brainqub3/meta_expert#10]
Anthropic recommends XML, and in testing other models, XML comes out ahead, especially for complex prompts. I'll work on converting and testing jar3d with XML. 

[Comparison of RAW, Markdown, XML, and JSON prompt formatting](https://youtu.be/W6Z0U11nnhA?si=DkTXNtjmr1tHILs4)

**Comment by john-adeojo** [comment]
Sounds like an interesting approach. I've found that it works well with Markdown, and is easy to read/update however it would be interesting to see results with XML.
