### ISSUE TITLE
It iterates in an indefinite loop to ask me questions.

### ISSUE THREAD

**Issue by BruceSuperProgramer** [brainqub3/meta_expert#7]
It iterates in an indefinite loop, repeatedly asking me questions. I’ve gone back and forth with Jar3d more than 10 times, but it never performs the search work. Instead, it continues to ask more questions based on the answers I provided to previous questions.

Is this a bug? 

If this is expected behavior, I believe users will quickly get bored with it.

**Comment by john-adeojo** [comment]
To end the question asking phase you need to type "/end". You should do this once you have provided enough requirements. I'll update the documentation to make this clear.

**Comment by BruceSuperProgramer** [comment]
Thanks, it works, and I am quite happy with the report results so far.I will keep trying.
