### ISSUE TITLE
Error in invoking model! No content in response

### ISSUE THREAD

**Issue by tonypius** [brainqub3/meta_expert#9]
<img width="1365" alt="Screenshot 2024-07-31 at 1 14 59 PM" src="https://github.com/user-attachments/assets/c9dcfb1a-e93c-43e4-9b14-eb32beeb313c">

Not able to even start the process

**Comment by john-adeojo** [comment]
Which model are you using?

**Comment by tonypius** [comment]
I tried adding keys of almost all. Currently I've keys for claude and groq. Still no luck. I've also added a serper key.

**Comment by john-adeojo** [comment]
You are getting 403 errors which is a permission error according to the official anthropic documentation. 
check it out here: https://docs.anthropic.com/en/api/errors
Seems your error is more to do with your account permisions on Anthropic.

**Comment by tonypius** [comment]
In the current push I'm able to choose the model. Previously it was always defaulting to anthropic. I'm closing this issue for now.
